package lt.Blogsite.GUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;

import lt.Blogsite.Classes.Blog;

public class AddCommentPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddCommentPanel
     */
    public AddCommentPanel(MainFrame mainFrame, Blog blog) {
        final MainFrame mf = mainFrame;
        final Blog b = blog;
        
        initComponents();
        
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (mf != null) {
                    mf.showBlog(b);
               }
            }
        });
        
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (mf != null) {
                    mf.addComment(b);
                    
               }
            }
        });
    }
    
    public ArrayList<String> getComment() {
        String str[] = jTextArea1.getText().split("\\r?\\n");
        ArrayList<String> list = new ArrayList<>(Arrays.asList(str)) ;
        System.out.println(list);
        return (ArrayList<String>)list.clone();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jButton1.setText("Back");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(jButton1);

        jButton2.setText("Add");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel1.add(jButton2);

        add(jPanel1, java.awt.BorderLayout.LINE_END);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
