package lt.Blogsite.GUI;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class BlogsPanel extends javax.swing.JPanel {

    /**
     * Creates new form BlogsPanel
     */
    public BlogsPanel(MainFrame mainFrame) {
        final MainFrame mf = mainFrame;
        
        initComponents();
        
        jButton1.setEnabled(false);
        jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (mf != null) {
                    mf.prevBlogs();
               }
            }
        });
        
        jButton2.setEnabled(false);
        jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (mf != null) {
                    mf.nextBlogs();
               }
            }
        });
        
        jButton3.setEnabled(false);
        jButton3.setVisible(false);
        jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (mf != null) {
                    mf.showAddBlog();
               }
            }
        });
        
        jButton4.setEnabled(false);
        jButton4.setVisible(false);
        jButton4.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (mf != null) {
                    mf.showAddUser();
               }
            }
        });
        
        jButton5.setEnabled(true);
        jButton5.setVisible(true);
        jButton5.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (mf != null) {
                    mf.searchFor();
               }
            }
        });
        
        jButton6.setEnabled(false);
        jButton6.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (mf != null) {
                    mf.showAllBlogs();
               }
            }
        });
    }
    
    public void addTo(Component component) {
        jPanel1.add(component);
    }
    
    public void removeFrom() {
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.repaint();
    }    
    
    public void setButtonsState(boolean prevEnabled, boolean nextEnabled, boolean admin, boolean allBlogs) {
        jButton1.setEnabled(prevEnabled);
        jButton2.setEnabled(nextEnabled);
        jButton3.setEnabled(admin);
        jButton3.setVisible(admin);
        jButton4.setEnabled(admin);
        jButton4.setVisible(admin);
        jButton6.setEnabled(allBlogs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jButton1.setText("Prev");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel2.add(jButton1);

        jButton2.setText("Next");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel2.add(jButton2);

        jButton3.setText("Add");
        jButton3.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel2.add(jButton3);

        jButton4.setText("Add user");
        jButton4.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel2.add(jButton4);

        jButton5.setText("Search");
        jButton5.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel2.add(jButton5);

        jButton6.setText("All news");
        jButton6.setMaximumSize(new java.awt.Dimension(100, 23));
        jButton6.setMinimumSize(new java.awt.Dimension(100, 23));
        jButton6.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel2.add(jButton6);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));
        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
